# Generated by Django 2.0.7 on 2018-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
